### ISSUE TITLE
missing example of a vs code command that is implemented in python

### ISSUE THREAD

**Issue by barkanido** [microsoft/vscode-python-tools-extension-template#151]
would love to see an example of how a simple command is registered in `package.json` and implemented in `lsp_server.py` using `pygls`. when trying to implement it myself based on this template, I had the need to pass the currently edited document URI to the command function.

to the best of my understanding, this requires some extra work under the `activate` function in `extenstion.ts`.
something along the lines of 
```typescript
context.subscriptions.push(
        onDidChangePythonInterpreter(async () => {
            await runServer();
        }),
        onDidChangeConfiguration(async (e: vscode.ConfigurationChangeEvent) => {
            if (checkIfConfigurationChanged(e, serverId)) {
                await runServer();
            }
        }),
        registerCommand(`${serverId}.restart`, async () => {
            await runServer();
        }),
        // new code here:
        registerCommand(`my_new_fancy_command`, () => {
            // some code to get the active lsp client
            if (lsClient) {
                if (vscode.window.activeTextEditor) {
                    const docUri = vscode.window.activeTextEditor.document.uri.toString();
                    // pass the active doc uril to the command
                    lsClient.sendRequest(`my_new_fancy_command`, [docUri]);
                }
            }
        }),
    );
```

the problem here is that in the current state of things, I cannot get a hold of the active LSP client. this is although it is a public global variable here. it is always undefined.

would love for help/ ideas here.
thanks for the great template!

**Comment by barkanido** [comment]
the above coding direction was a mistake since it fails the creation of the client. Actually, this is why it stays undefined (`restartServer` fails with an exception and returns `undefined`).
I wonder, than, how should I implemet this?
where can I code the
```typescript
const docUri = vscode.window.activeTextEditor.document.uri.toString();
```
and pass this argument to the python code?

**Comment by karthiknadig** [comment]
Here is an example of a command registered from package.json, and implemented in TS, with actual handling in LSP setver:
package.json: https://github.com/astral-sh/ruff-vscode/blob/e675c39f14db906d74aa4c6af782f7f4fb081b90/package.json#L200-L204
extension.ts: https://github.com/astral-sh/ruff-vscode/blob/e675c39f14db906d74aa4c6af782f7f4fb081b90/src/extension.ts#L186-L210
lsp_server.py: https://github.com/astral-sh/ruff-lsp/blob/5cc6f02fb885b30dd294624471a7f19636ae86a4/ruff_lsp/server.py#L661-L669

**Comment by karthiknadig** [comment]
The minimum thing that is needed is the `lsClient` if you want to handle the command in the LSP server. So, you need to figure out why your client is failing to start. If you can provide me with more details on what is failure or error I can help debug this further.

**Comment by barkanido** [comment]
The client was `undefined` since `restartServer` was erroring because of a function was registered twice.

To me, the relationship between what is declared in `package.json`, calls to `registerCommand`, and actual implementations in the backend was not clear.

I initially understood that I need to implement in the backend everything that is present in the manifest `commands` part (`package.json`) and everything is magically connected for you. However, the API of `registerCommand` confused me.

Also, the API of `executeCommand` has many overloads and not docs. Or have I missed it?

When and if should one use `vscode.commands.executeCommand` instead? And what are the differences?

**Comment by karthiknadig** [comment]
> Also, the API of executeCommand has many overloads and not docs. Or have I missed it?

You should not have to use `executeCommand ` unless you want to programmatically trigger your command. In your case if you are adding a command for your user to trigger, then you don't need to use this.

> When and if should one use `vscode.commands.executeCommand` instead? 

You would likely use it for testing primarily, or in rare cases where you want to trigger a command on behalf of the user.

> And what are the differences?

The `executeCommand` is designed to run any command, so it has lots of overloads to allow passing in any type of argument. 
```ts
// Example with no arguments:
executeCommand('workbench.action.reloadWindow');
// Example with 1 argument:
executeCommand('python.triggerEnvSelection', uri);

executeCommand('someCommandName', arg1, arg2, arg3, ..., argN);
```
