### ISSUE TITLE
Do not attempt to launch any servers in case when Python is not installed

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-python-tools-extension-template#25]
Something like:
```typescript
public async hasInterpreters(): Promise<boolean> {
    const onAddedToCollection = createDeferred();
    // Watch for collection changed events.
    this.api.onChanged(async (e: PythonEnvCollectionChangedEvent) => {
        if (e.new) {
            onAddedToCollection.resolve();
        }
    });
    const initialEnvs = this.api.getEnvs();
    if (initialEnvs.length > 0) {
        return true;
    }
    await Promise.race([onAddedToCollection.promise, this.api.getRefreshPromise()]);
    return this.api.getEnvs().length > 0;
}
```
can be built off using the proposed discovery API.

**Comment by karthiknadig** [comment]
@karrtikr @luabud Since this particular issue is there to reduce the number of notifications we pop; do you suggest that we just log this

@karrtikr I don't want this template to have any more knowledge about how the discovery occurs in the python extension. I think a better approach is, this extension asks for interpreter, and gets back `undefined` if nothing is available. When one becomes available and is selected it will trigger interpreter changed event. that should start the server.

**Comment by luabud** [comment]
I agree 👍

**Comment by karthiknadig** [comment]
To Do:
- [ ] If python is missing log to output channel.
- [ ] If user runs restart command, show notification that python is not selected. With a button to trigger python selection.

**Comment by karrtikr** [comment]
> If user runs restart command, show notification that python is not selected. With a button to trigger python selection.

`python.triggerEnvSelection` command can be used if no interpreter is returned via the API to trigger a prompt asking to select an interpreter.

**Comment by karrtikr** [comment]
Can you please link the PRs/commits fixing this in all 4 repositories?

**Comment by karrtikr** [comment]
We should also add a milestone so these can be verified.

**Comment by karthiknadig** [comment]
pull requests for the template:
https://github.com/microsoft/vscode-python-tools-extension-template/pull/30
https://github.com/microsoft/vscode-python-tools-extension-template/pull/34

Pull request for pylint:
https://github.com/microsoft/vscode-pylint/pull/147

Pull request for black:


Pull request for isort:


Note that i did create TPI to test some settings which used proposed API. There is no direct way to test the template other than using the pylint, black, isort extensions. I will schedule a mini bug bash for those next week.
