### ISSUE TITLE
Extension fails to import `bundled` module

### ISSUE THREAD

**Issue by jreese** [microsoft/vscode-python-tools-extension-template#42]
Hi, I cloned the template and followed the instructions to replace all the various bits for my own module. However, when I try to run/debug the extension, it fails to start correctly because it can't find/import the `bundled` module from `server.py`. I tried adding the root of the extension to `sys.path`, but it still can't find the module.

Relevant section of extension logs:

```
Name: µfmt
Module: ufmt
[DEBUG 2022-7-5 16:12:47.701]: Configuration: {"name":"µfmt","module":"ufmt"}
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
[INFO 2022-7-5 16:12:48.146]: Server run command: /Users/jreese/workspace/trailrunner/.venv/bin/python /Users/jreese/workspace/vscode-ufmt/bundled/tool/_debug_server.py
[INFO 2022-7-5 16:12:48.154]: Server: Start requested.
[DEBUG 2022-7-5 16:12:48.154]: Server State: Starting
Traceback (most recent call last):
  File "/Users/jreese/workspace/vscode-ufmt/bundled/tool/_debug_server.py", line 43, in <module>
    runpy.run_path(SERVER_PATH, run_name="__main__")
  File "/Users/jreese/.pyenv/versions/3.10.4/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/jreese/.pyenv/versions/3.10.4/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/jreese/.pyenv/versions/3.10.4/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jreese/workspace/vscode-ufmt/bundled/tool/server.py", line 40, in <module>
    from bundled.tool.utils import RunResult
ModuleNotFoundError: No module named 'bundled'
[Info  - 4:12:53 PM] Connection to server got closed. Server will restart.
```

Full log output: https://gist.github.com/jreese/72f9ee83a0cd6ef63918026d8a26e0d3

Extension repo: https://github.com/omnilib/vscode-ufmt

**Comment by karthiknadig** [comment]
@jreese You can remove that line. I don't see that in the template repo. You should not need that line.
```
from bundled.tool.utils import RunResult
```
If you need to access RunResult object, just use `utils.RunResult` . utils is already imported.

**Comment by jreese** [comment]
Ah ha, sorry. I referenced `RunResult` elsewhere without using `utils.RunResult`, so I guess that got added automatically by VSCode without me catching it. I updated that reference and removed the import, and that did fix the issue.

Thank you, and sorry for not catching that myself 😅
