### ISSUE TITLE
How to handle bundling native deps

### ISSUE THREAD

**Issue by amyreese** [microsoft/vscode-python-tools-extension-template#50]
I built the [µfmt extension](https://marketplace.visualstudio.com/items?itemName=omnilib.ufmt) following this template, which results in bundling µfmt and its dependencies in the vsix file, as expected. 

However, some of these dependencies have native extensions (eg, [LibCST](https://libcst.rtfd.io) for parsing Python code). LibCST in particular will be requiring these native extensions in the future, with no fallback to pure-python, as that would greatly reduce performance and increase the ongoing maintenance cost of the package.

I've used the [vscode-platform-specific-sample](https://github.com/microsoft/vscode-platform-specific-sample) project to add builds for multiple platforms, but this does not seem to be a complete solution for bundling native Python extensions.

The problem is that these native extensions are specific to the major version of the Python runtime, and (afaict) VS Code does not seem to expose the runtime baked into the application in such a way that I can target my vsix builds to the appropriate Python versions, making it difficult to guarantee that I'm building a compatible extension to use with the bundled version of µfmt.

As of right now, it seems that the `nox --session setup` command simply builds/bundles a native extension based on whatever version of Python my nox binary was installed with:

Installed nox with 3.9.9:

```
(venv) amethyst@mordin ~/workspace/vscode-ufmt platforms± » which nox
/Users/amethyst/workspace/vscode-ufmt/venv/bin/nox
(venv) amethyst@mordin ~/workspace/vscode-ufmt platforms± » python -V
Python 3.9.9
(venv) amethyst@mordin ~/workspace/vscode-ufmt platforms± » find bundled/libs | grep .so$
bundled/libs/libcst/_parser/parso
bundled/libs/libcst/native.cpython-39-darwin.so
```

Installed nox with 3.10.6:

```
(venv) amethyst@mordin ~/workspace/vscode-ufmt platforms± » python -V
Python 3.10.6
(venv) amethyst@mordin ~/workspace/vscode-ufmt platforms± » find bundled/libs | grep .so$
bundled/libs/libcst/_parser/parso
bundled/libs/libcst/native.cpython-310-darwin.so
```

The .so files installed into `bundled/libs/` are the only ones that make it into the vsix file when I finally run `vsce package`, but this means that if I pick the wrong runtime (that doesn't match the major version used by VSCode), then users of the vsix (that opt to use the bundled version of µfmt) will not be able to import/load the native extension, resulting in worse performance, and eventually break the bundled version of µfmt when LibCST removes the pure python implementation.

Is there any way to know/detect what version of the runtime is bundled with VS Code? Is there a way to use that bundled runtime to build a virtualenv and/or install nox? Is that something that can be done from a Github action? Or do I just need to depend on users having a local runtime/virtualenv and drop support for bundling a build of µfmt altogether?

Thank you!

**Comment by karthiknadig** [comment]
@amyreese You don't really need to worry about selecting the right bundled version of the compiled binary. Python will select this for you. If you want to see code to package various version of the compiled binary, then see this example https://github.com/microsoft/vscode-black-formatter/blob/4e8aeb3376c4fb5eacc97229c7390636762a057e/noxfile.py#L270-L281

In the black extension, I had to bundle a specific version of the `typed_ast` for python 3.7 which is only available as compiled package. You can adapt that code to install download the libs for various versions. Build the requirements.txt using the lowest version of python you want to support. Then use the above script to package the libs for all platforms and all python ABIs from the lowest to 3.10.

If you really want to optimize you could, adapt the script to only pull in platform specific versions and package them as separate visx for each platform, just bundle the lowest - 3.10 ABI libs for each platform.

**Comment by amyreese** [comment]
Thanks for pointing me in that direction.

For anyone else needing to do, I ended up doing a `pip download` once for each supported Python version, to fetch all of the wheels into a single directory, and then extract their native extensions into the `bundled/libs` directory: https://github.com/omnilib/vscode-ufmt/blob/main/noxfile.py#L36

And I combined that with OS/arch-specific VSIX builds, resulting in a platform-specific VSIX file that contains multiple versions of the native extensions for that platform: https://github.com/omnilib/vscode-ufmt/blob/main/.github/workflows/build.yml#L11

Thanks again!
