### ISSUE TITLE
Update recommended extensions to contain prettier

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode-python-tools-extension-template#65]
`extensions.json` seems to be missing prettier: `esbenp.prettier-vscode`. But the pipelines of say Black extension, seems to be checking linting which relies on prettier.

**Comment by karthiknadig** [comment]
you don't need prettier extension. you just need prettier the node module.

**Comment by karrtikr** [comment]
What's the reasoning behind expecting template users to use a node module over the extension? I think `settings.json` could specify:
```
"[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
},
```
and we could recommend prettier extension for a transparent smoother experience.
