### ISSUE TITLE
Is this a template to implement code extension using Python?

### ISSUE THREAD

**Issue by ws1088** [microsoft/vscode-python-tools-extension-template#67]
Hi,

I am a little bit confused if this template will work with any type of document? For example, can I write a vscode extension which handle `.csv` file using Python?

Do users of the extension created with this need to install Python?

Thanks!

**Comment by karthiknadig** [comment]
This extension can work with any file, you will have to update the `package.json` and `server.ts`. Specifically, these lines:
https://github.com/microsoft/vscode-python-tools-extension-template/blob/main/package.json#L40-L44
https://github.com/microsoft/vscode-python-tools-extension-template/blob/main/src/common/server.ts#L87-L94

 This extension requires python to run the server. The extension does not ship with python. But it uses the python extension ([ms-python.python](https://marketplace.visualstudio.com/items?itemName=ms-python.python)), and that extension can guide users on how to install python if they don't have one. If they have one the python extension will select it, and extensions built using this template can use it.

**Comment by karthiknadig** [comment]
Closing this issue. Please let me know if you have further questions.
