### ISSUE TITLE
Change the `TODO` in the license file

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-python-tools-extension-template#74]
It currently says:

https://github.com/microsoft/vscode-python-tools-extension-template/blob/53d1c62baba6460ae74aae31b715855fb1bdcf12/LICENSE#L3

But that is actually correct for the code coming from the template. That `TODO` should be moved to its own line for folks to add their own names to the license while retaining the Microsoft copyright for the code they got from this repo.

**Comment by karthiknadig** [comment]
@brettcannon I can move that to the end of the file. Any instructional text to put there?

**Comment by brettcannon** [comment]
It doesn't have to be at the end if the person wants to keep the MIT license. They just need to make sure to leave Microsoft's name there.

Probably something along the lines of `# TODO: If you want to keep using the MIT license, add your name here. To change the license, prepend it to this file.` Otherwise we can ask CELA for advice.
