### ISSUE TITLE
atexit.register decorator causes exception

### ISSUE THREAD

**Issue by eddyg** [microsoft/vscode-python-tools-extension-template#83]
I [submitted a PR](https://github.com/charliermarsh/vscode-ruff/issues/53) to fix an issue I noticed in the Ruff extension for VS Code.

Later I realized the code is from this template.

If I opened a PR to make the same change here, would it be merged?

Thanks for any insight!

**Comment by karthiknadig** [comment]
Yes, we can accept PRs for this template.
